### ISSUE TITLE
Error Running Example

### ISSUE THREAD

**Issue by stevepop** [JeffreyWay/laravel-mix-example#3]
I followed the steps to install and run the example but got the following errors when I ran 
npm run dev

```
> @ dev /Users/steve/devapps/sandbox/laravel-mix-example
> cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/steve/devapps/sandbox/laravel-mix-example/node_modules/laravel-mix/src/index.js:1
(function (exports, require, module, __filename, __dirname) { let path = require('path');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/steve/devapps/sandbox/laravel-mix-example/node_modules/laravel-mix/setup/webpack.config.js:3:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steve/devapps/sandbox/laravel-mix-example/npm-debug.log
```

**Comment by stevepop** [comment]
I discovered this was due to the correct webpack version not being installed. Issue was resolved when I manually installed webpack 2.2.0.

**Comment by jericopulvera** [comment]
@stevepop how did you manually install the webpack 2.2.0? are you sure it's version 2.2.0?

**Comment by Germey** [comment]
@jericopulvera  https://webpack.js.org/get-started/install-webpack/

Note that this documentation is for webpack 2, for which there is not yet a stable release. You can get the most recent beta by installing with the beta tag (see below).

Global Installation

```
npm install webpack@beta -g
```

The webpack command is now available globally.

Then run
 
```
webpack -v
```
It shows 2.2.0
